name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          # Clone to temporary directory first
          mkdir -p /tmp/healthgate_tmp
          cd /tmp/healthgate_tmp
          
          # Fresh clone of the repository
          git clone https://github.com/9asdaoui/HealthGate.git .
          
          # Prepare target directory
          mkdir -p ~/domains/healthgate.azizbenmallouk.com/public_html/
          
          # Sync files (rsync preserves permissions and is efficient)
          rsync -av --delete \
            --exclude='.git/' \
            --exclude='storage/app/*' \
            --exclude='storage/logs/*' \
            --exclude='storage/framework/cache/*' \
            --exclude='.env' \
            ./ ~/domains/healthgate.azizbenmallouk.com/public_html/
          
          # Enter project directory
          cd ~/domains/healthgate.azizbenmallouk.com/public_html/
          
          # Set file permissions
          chmod -R 755 .
          chmod -R 777 storage bootstrap/cache
          
          # Copy .env file if it doesn't exist
          [ -f .env ] || cp .env.example .env
          
          # Update Composer to version 2
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php composer-setup.php --install-dir=/tmp --filename=composer
          php -r "unlink('composer-setup.php');"
          mv /tmp/composer ~/bin/composer
          chmod +x ~/bin/composer
          export PATH=$PATH:~/bin
          
          # Install dependencies using Composer 2
          ~/bin/composer install --no-dev --optimize-autoloader
          
          # Run Laravel commands
          php artisan key:generate --force
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          
          # Cleanup
          rm -rf /tmp/healthgate_tmp