name: Deploy Application

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Production
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
            # Check if directory exists
            cd domains/healthgate.azizbenmallouk.com/public_html/ || exit 1
            # Check if it's a git repository
            git status || echo "Not a git repository, initializing" && git init
            # Set remote if needed
            git remote -v || git remote add origin https://github.com/9asdaoui/HealthGate.git
            # Pull code
            git pull origin main || git clone https://github.com/9asdaoui/HealthGate.git .
            
            # Rest of your commands
            composer install --no-interaction --prefer-dist --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear
            php artisan optimize